openapi: 3.0.3
info:
  title: ClimeTune API
  version: '1.0'
  x-logo:
    url: ''
  contact:
    name: Marc Valsells Niubó
    url: https://valsells.me
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
paths:
  /place/:
    post:
      summary: Adds a new place
      description: Adds a new place to the database
      operationId: addPlace
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Place'
        required: true
      responses:
        '200':
          description: Place added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Place'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: string
                example: Invalid input
        '409':
          description: Place already exists
          content:
            application/json:
              schema:
                type: string
                example: Place already exists
    get:
      summary: Returns all places
      description: Get a list of all places in the database
      operationId: getPlaces
      responses:
        '200':
          description: Place added
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Place'

  /place/{id}:
    get:
      summary: Returns a place
      description: Returns the place with the given id
      operationId: getPlaces
      responses:
        '200':
          description: Place added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Place'
        '404':
          description: Place does not exist
          content:
            application/json:
              schema:
                type: string
                example: Place does not exist
    put:
      summary: Updates an existing place
      description: ''
      operationId: updatePlace
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Place'
        required: true
      responses:
        '200':
          description: Place added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Place'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: string
                example: Invalid input
        '404':
          description: Place does not exist
          content:
            application/json:
              schema:
                type: string
                example: Place does not exist
    delete:
      summary: Deletes an existing place
      description: ''
      operationId: deletePlace
      responses:
        '200':
          description: Place removed
          content:
            application/json:
              schema:
                type: string
                example: Place removed
        '404': 
          description: Place does not exist
          content:
            application/json:
              schema:
                type: string
                example: Place does not exist
        '412':
          description: Place has rain data
          content:
            application/json:
              schema:
                type: string
                example: Place has rain data
components:
  securitySchemes: {}
  schemas:
    Place:
      type: object
      properties:
        id:
          type: integer
          format: int32
          minimum: 1
          maximum: 2147483647
        name:
          type: string
          maxLength: 40
        address:
          type: string
          maxLength: 100
        postalCode:
          type: string
          maxLength: 10
        city:
          type: string
          maxLength: 100
        countryCode:
          type: string
          maxLength: 2
        latitude:
          type: number
          format: float
          minimum: -90
          maximum: 90
        longitude:
          type: number
          format: float
          minimum: -180
          maximum: 180
    Rain:
      type: object
      properties:
        id:
          type: integer
          format: int32
          minimum: 1
          maximum: 2147483647
        date:
          type: string
          format: date
        litersMsq:
          type: number
          format: float
          minimum: 0
          maximum: 10000
        observations:
          type: string
          maxLength: 750
        id_place:
          type: integer
          format: int32
          minimum: 1
          maximum: 2147483647
  headers: {}
  responses: {}
  parameters: {}
tags: []
servers:
  - url: https://api.climatune.valsells.me/
    description: ''
    variables: {}
security: []
